export const mockStories = [
  {
    id: 'story1',
    avatar: 'https://picsum.photos/300/300',
    username: 'John Doe',
    company: 'Acme Corp',
    time: '2h ago',
    title: 'Exciting Update from Acme!',
    content: 'We just launched a new feature that will make your workflow smoother and more efficient. Try it out and let us know what you think!',
    image: 'https://picsum.photos/seed/sample/600/300',
    onItemPress: 'route:/story/:id',
  },
  {
    id: 'story2',
    avatar: 'https://picsum.photos/300/300',
    username: 'Jane Smith',
    company: 'Productive.io',
    time: '1d ago',
    title: 'Reflections on Remote Work',
    content: 'After two years of working remotely, I’ve learned a lot about balance, boundaries, and building trust with my team...',
    image: null,
    onItemPress: 'route:/story/:id',
  },
  {
    id: 'story3',
    avatar: 'https://picsum.photos/300/300',
    username: 'Carlos Martinez',
    company: 'TechFlow',
    time: '3h ago',
    title: 'React vs Svelte: Which Should You Choose?',
    content: 'I compared React and Svelte in a real-world project. Here are my thoughts on performance, developer experience, and learning curve.',
    image: null,
    onItemPress: 'route:/story/:id',
  },
  {
    id: 'story4',
    avatar: 'https://picsum.photos/300/300',
    username: 'Fatima Al Zahra',
    company: 'DesignBloom',
    time: '6h ago',
    title: 'Minimalism in UX Design',
    content: 'A good design is not when there is nothing more to add, but when there is nothing left to take away.',
    image: 'https://picsum.photos/seed/sample/600/300',
    onItemPress: 'route:/story/:id',
  },
  {
    id: 'story5',
    avatar: 'https://picsum.photos/300/300',
    username: 'Luca Bianchi',
    company: 'DataDive',
    time: '15m ago',
    title: '5 Python Tricks for Data Scientists',
    content: 'Want to write cleaner, faster Python code? These five tricks have saved me countless hours when working with pandas and NumPy.',
    image: null,
    onItemPress: 'route:/story/:id',
  },
  {
    id: 'story6',
    avatar: 'https://picsum.photos/300/300',
    username: 'Emily Chen',
    company: 'CloudHive',
    time: '4d ago',
    title: 'Celebrating 5 Years at CloudHive!',
    content: 'Today marks 5 years since I joined CloudHive. Grateful for the growth, the mentorship, and the friendships along the way.',
    image: 'https://picsum.photos/seed/sample/600/300',
    onItemPress: 'route:/story/:id',
  },
  {
    id: 'story7',
    avatar: 'https://picsum.photos/300/300',
    username: 'Mohammed Al-Rashid',
    company: 'OpenFinance',
    time: '9h ago',
    title: 'Open Banking: The Future of Fintech',
    content: 'Exploring the challenges and opportunities of open banking regulations in the Middle East and how startups can prepare.',
    image: null,
    onItemPress: 'route:/story/:id',
  },
  {
    id: 'story8',
    avatar: 'https://picsum.photos/300/300',
    username: 'Sara Novak',
    company: 'RemoteTeam',
    time: '2d ago',
    title: 'How We Built Culture Remotely',
    content: 'From onboarding rituals to virtual coffee chats — here’s how we kept our company culture strong across time zones.',
    image: 'https://picsum.photos/seed/sample/600/300',
    onItemPress: 'route:/story/:id',
  },
  {
    id: 'story9',
    avatar: 'https://picsum.photos/300/300',
    username: 'Andrew Kim',
    company: 'ZeroCarbon',
    time: '12h ago',
    title: 'Going Carbon Neutral in 2025',
    content: 'We just announced our roadmap to become carbon neutral by 2025. Read more about our strategy and the partnerships driving it.',
    image: 'https://picsum.photos/seed/sample/600/300',
    onItemPress: 'route:/story/:id',
  },
  {
    id: 'story10',
    avatar: 'https://picsum.photos/300/300',
    username: 'Natalie Roberts',
    company: 'GrowthLoop',
    time: '30m ago',
    title: '10 Tips for Better Product Demos',
    content: 'A great product demo doesn’t just show features — it tells a story. Here are 10 tips I use before every sales call.',
    image: null,
    onItemPress: 'route:/story/:id',
  },
  {
    id: 'story11',
    avatar: 'https://picsum.photos/300/300',
    username: 'Ravi Patel',
    company: 'AIForge',
    time: '5h ago',
    title: 'What GPT-5 Means for Developers',
    content: 'As LLMs evolve, so must we. Here’s what I believe GPT-5 will change in the way we build and scale software.',
    image: 'https://picsum.photos/seed/sample/600/300',
    onItemPress: 'route:/story/:id',
  },
];

export const mockProjects = [
  {
    id: 'p1',
    title: 'AI Code Generator',
    description: 'A smart tool to write code from plain English.',
    image: 'https://picsum.photos/seed/genesis/600/300',
    agent: 'Steward',
    status: 'done',
  },
  {
    id: 'p2',
    title: 'Open Bible Commentary',
    description: 'A crowdsourced commentary platform.',
    image: "https://picsum.photos/seed/logosmind/600/300",
    agent: 'Theosynth',
    status: 'in progress',
  },
  {
    id: 'p3',
    title: 'EcoHacks',
    description: 'A green tech initiative for sustainable living.',
    image: 'https://picsum.photos/seed/pitchai/600/300',
    agent: 'CrossAI',
    status: 'submitted',
  },
  {
    id: 'p4',
    title: 'Tiny Dev Tools',
    description: 'A collection of tiny, useful utilities for developers.',
    image: null,
    agent: 'N/A',
    status: 'concept',
  },
];

const mockItems = [
  {
    title: "How to Build a Full-Stack App",
    intro: "An easy-to-follow guide to building scalable full-stack applications using Next.js and Firebase.",
    username: "devguru",
    author: "Alex Dev",
    project: "FullStackProject",
    community: "CodeMasters",
    tags: ["Next.js", "Firebase", "WebDev"],
    shortIntro: true,
    highlight: true,
    banner: "https://picsum.photos/300/300", // or null
    avatar: null,
    onItemPress: "route:/id",
  },
  {
    title: "Designing Scalable UI Systems",
    intro: "Learn how to use Tailwind CSS and component libraries to create scalable UIs.",
    username: "uidesigner",
    author: "Emily Design",
    project: "DesignKit",
    community: "UIHub",
    tags: ["Tailwind", "Design", "UX"],
    shortIntro: false,
    highlight: false,
    banner: "https://picsum.photos/300/300",
    avatar: null,
    onItemPress: "route:/id",
  },
];

export default {
    mockItems, mockProjects, mockStories
}